name: "Setup OCI NSG"
description: "Deploy and destroy Terraform infrastructure with OCI provider and S3 backend"
branding:
  icon: "cloud"
  color: "blue"

inputs:
  # AWS S3 Backend Configuration
  aws-access-key-id:
    description: "AWS Access Key ID for S3 backend"
    required: true
  aws-secret-access-key:
    description: "AWS Secret Access Key for S3 backend"
    required: true
  aws-region:
    description: "AWS region for S3 backend"
    required: false
    default: "ap-southeast-1"
  backend-key:
    description: "S3 backend key path (defaults to repository name)"
    required: false
    default: "${{ github.repository }}/terraform.tfstate"

  # OCI Provider Configuration
  oci-user-id:
    description: "OCI CLI User OCID"
    required: true
  oci-tenancy-id:
    description: "OCI CLI Tenancy OCID"
    required: true
  oci-fingerprint:
    description: "OCI CLI Fingerprint"
    required: true
  oci-private-key:
    description: "OCI CLI Private Key Content"
    required: true
  oci-region:
    description: "OCI Region"
    required: true
  oci-compartment-id:
    description: "OCI Compartment OCID"
    required: true
  oci-nsg-id:
    description: "OCI Network Security Group ID"
    required: true

  # Terraform Configuration
  terraform-version:
    description: "Terraform version to use"
    required: false
    default: "1.13.0"
  terraform-working-directory:
    description: "Directory containing Terraform files in the action repository"
    required: false
    default: "."
  auto-destroy:
    description: "Whether to automatically destroy resources after apply"
    required: false
    default: "true"
  apply-infrastructure:
    description: "Whether to apply infrastructure changes"
    required: false
    default: "true"

outputs:
  runner-ip:
    description: "Public IP address of the GitHub Actions runner"
    value: ${{ steps.get-ip.outputs.ipv4 }}
  terraform-output:
    description: "Terraform output in JSON format"
    value: ${{ steps.output.outputs.stdout }}

runs:
  using: "composite"
  steps:
    # Checkout the action's repository (contains Terraform files)
    - name: Checkout
      uses: actions/checkout@v4

    # Configure AWS credentials for S3 backend
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    # Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform-version }}
        terraform_wrapper: false

    # Get runner's public IP
    - name: Get Runner's Public IP
      id: get-ip
      shell: bash
      run: |
        PUBLIC_IP=$(curl -s 'https://api.ipify.org')
        echo "ipv4=$PUBLIC_IP" >> $GITHUB_OUTPUT
        echo "Runner IP: $PUBLIC_IP"

    # Initialize Terraform
    - name: Terraform Init
      shell: bash
      working-directory: ${{ inputs.terraform-working-directory }}
      run: terraform init -backend-config="key=${{ inputs.backend-key }}"
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}

    # Terraform Plan
    - name: Terraform Plan
      if: ${{ inputs.apply-infrastructure == 'true' }}
      shell: bash
      working-directory: ${{ inputs.terraform-working-directory }}
      run: terraform plan -input=false
      env:
        # OCI Provider Environment Variables
        OCI_CLI_USER: ${{ inputs.oci-user-id }}
        OCI_CLI_TENANCY: ${{ inputs.oci-tenancy-id }}
        OCI_CLI_FINGERPRINT: ${{ inputs.oci-fingerprint }}
        OCI_CLI_KEY_CONTENT: ${{ inputs.oci-private-key }}
        OCI_CLI_REGION: ${{ inputs.oci-region }}
        # Terraform Variables
        TF_VAR_tenancy_id: ${{ inputs.oci-tenancy-id }}
        TF_VAR_user_id: ${{ inputs.oci-user-id }}
        TF_VAR_region: ${{ inputs.oci-region }}
        TF_VAR_compartment_id: ${{ inputs.oci-compartment-id }}
        TF_VAR_nsg_id: ${{ inputs.oci-nsg-id }}
        TF_VAR_api_fingerprint: ${{ inputs.oci-fingerprint }}
        TF_VAR_api_private_key: ${{ inputs.oci-private-key }}
        TF_VAR_ingress_cidr: ${{ steps.get-ip.outputs.ipv4 }}/32

    # Apply Terraform changes
    - name: Terraform Apply
      if: ${{ inputs.apply-infrastructure == 'true' }}
      shell: bash
      working-directory: ${{ inputs.terraform-working-directory }}
      run: terraform apply -auto-approve -input=false
      env:
        # OCI Provider Environment Variables
        OCI_CLI_USER: ${{ inputs.oci-user-id }}
        OCI_CLI_TENANCY: ${{ inputs.oci-tenancy-id }}
        OCI_CLI_FINGERPRINT: ${{ inputs.oci-fingerprint }}
        OCI_CLI_KEY_CONTENT: ${{ inputs.oci-private-key }}
        OCI_CLI_REGION: ${{ inputs.oci-region }}
        # Terraform Variables
        TF_VAR_tenancy_id: ${{ inputs.oci-tenancy-id }}
        TF_VAR_user_id: ${{ inputs.oci-user-id }}
        TF_VAR_region: ${{ inputs.oci-region }}
        TF_VAR_compartment_id: ${{ inputs.oci-compartment-id }}
        TF_VAR_nsg_id: ${{ inputs.oci-nsg-id }}
        TF_VAR_api_fingerprint: ${{ inputs.oci-fingerprint }}
        TF_VAR_api_private_key: ${{ inputs.oci-private-key }}
        TF_VAR_ingress_cidr: ${{ steps.get-ip.outputs.ipv4 }}/32

    # Get Terraform outputs
    - name: Get Terraform Output
      if: ${{ inputs.apply-infrastructure == 'true' }}
      id: output
      shell: bash
      working-directory: ${{ inputs.terraform-working-directory }}
      run: |
        OUTPUT=$(terraform output -json)
        echo "stdout=$OUTPUT" >> $GITHUB_OUTPUT
      env:
        # OCI Provider Environment Variables
        OCI_CLI_USER: ${{ inputs.oci-user-id }}
        OCI_CLI_TENANCY: ${{ inputs.oci-tenancy-id }}
        OCI_CLI_FINGERPRINT: ${{ inputs.oci-fingerprint }}
        OCI_CLI_KEY_CONTENT: ${{ inputs.oci-private-key }}
        OCI_CLI_REGION: ${{ inputs.oci-region }}

    # Destroy infrastructure if auto-destroy is enabled
    - name: Terraform Destroy
      if: ${{ inputs.auto-destroy == 'true' }}
      shell: bash
      working-directory: ${{ inputs.terraform-working-directory }}
      run: terraform destroy -auto-approve -input=false
      env:
        # OCI Provider Environment Variables
        OCI_CLI_USER: ${{ inputs.oci-user-id }}
        OCI_CLI_TENANCY: ${{ inputs.oci-tenancy-id }}
        OCI_CLI_FINGERPRINT: ${{ inputs.oci-fingerprint }}
        OCI_CLI_KEY_CONTENT: ${{ inputs.oci-private-key }}
        OCI_CLI_REGION: ${{ inputs.oci-region }}
        # Terraform Variables
        TF_VAR_tenancy_id: ${{ inputs.oci-tenancy-id }}
        TF_VAR_user_id: ${{ inputs.oci-user-id }}
        TF_VAR_region: ${{ inputs.oci-region }}
        TF_VAR_compartment_id: ${{ inputs.oci-compartment-id }}
        TF_VAR_nsg_id: ${{ inputs.oci-nsg-id }}
        TF_VAR_api_fingerprint: ${{ inputs.oci-fingerprint }}
        TF_VAR_api_private_key: ${{ inputs.oci-private-key }}
        TF_VAR_ingress_cidr: ${{ steps.get-ip.outputs.ipv4 }}/32
